#!/usr/bin/env python3
"""Point the Version 2 strategies at different MT5 accounts from Version 1.

Version 2's config sidecars were generated by copying Version 1's, so out of
the box every Version 2 strategy trades the SAME account as the Version 1
script it replaces. That is fine for a cutover — one replaces the other — but
wrong for running the two side by side, which is the whole point of a shadow
deployment: both copies would place orders against one balance and neither
result would mean anything.

Give it a mapping and it rewrites only MT5_BRIDGE_URL and MT5_API_KEY, leaving
the magic alone. The magic is deliberately NOT changed: it is what identifies a
strategy in the account history forever, and the registry rejects a collision.
Two strategies on one magic are only distinguishable because they trade
different accounts.

    python scripts/repoint_v2_accounts.py --map accounts.json
    python scripts/repoint_v2_accounts.py --map accounts.json --dry-run

accounts.json is {strategy_id: {"MT5_BRIDGE_URL": "...", "MT5_API_KEY": "..."}}
or, to send every strategy to one account, {"*": {...}}.
"""

import argparse
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIVE = os.path.join(HERE, "Live")


def v2_configs():
    """(strategy_id, config path) for every Version 2 strategy."""
    out = []
    for py in sorted(glob.glob(os.path.join(LIVE, "*", "s1*.py"))
                     + glob.glob(os.path.join(LIVE, "*", "s2*.py"))):
        if py.endswith("_core.py"):
            continue
        cfg = py[:-3] + ".json"
        if not os.path.exists(cfg):
            continue
        src = open(py, encoding="utf-8").read()
        m = re.search(r"""\bid=["']([A-Za-z0-9._-]+)["']""", src)
        if not m:
            core = os.path.join(os.path.dirname(py), "s21_core.py")
            if os.path.exists(core):
                m = re.search(r"""id=["']([A-Za-z0-9._-]+)["']""",
                              open(core, encoding="utf-8").read())
        if m:
            out.append((m.group(1), cfg))
    return out


def account_of(url):
    parts = (url or "").rstrip("/").split("/")
    return "/".join(parts[-2:]) if len(parts) >= 2 else "?"


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--map", required=True, help="JSON mapping file")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    mapping = json.load(open(args.map))
    default = mapping.get("*")

    configs = v2_configs()
    if not configs:
        print("no Version 2 configs found under Live/", file=sys.stderr)
        return 1

    changed = 0
    for sid, path in configs:
        want = mapping.get(sid, default)
        cfg = json.load(open(path))
        before = account_of(cfg.get("MT5_BRIDGE_URL"))
        if not want:
            print(f"  SKIP   {sid:26} no mapping (stays on {before})")
            continue
        after = account_of(want.get("MT5_BRIDGE_URL"))
        if before == after:
            print(f"  SAME   {sid:26} already on {after}")
            continue
        print(f"  MOVE   {sid:26} {before} -> {after}")
        if not args.dry_run:
            for k in ("MT5_BRIDGE_URL", "MT5_API_KEY"):
                if k in want:
                    cfg[k] = want[k]
            with open(path, "w") as f:
                json.dump(cfg, f, indent=4)
        changed += 1

    print()
    print(f"  {changed} config(s) {'would be ' if args.dry_run else ''}repointed")
    if changed and not args.dry_run:
        print("  Magic numbers are unchanged — they identify a strategy in the")
        print("  account history and must stay stable.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
